### PR TITLE
tracking pr for partial manifest load: mount(path, manifest)

### PR DESCRIPTION
**Pull request by dominictarr**
starting on this and wrapping my head around how this can fit together.
so far i have tidied up things to more clearly be about calling a method at a path into the tree.
this will then be able to attach directly to the "mount" bit.

### CODE REVIEW

**Comment by dominictarr** [comment]
Also shaved off 30 lines!

**Comment by dominictarr** [comment]
this tidies up muxrpc _a lot_. This is currently backwards compatible.
I want to simplify this a bit more, but that will require corresponding changes to secret-stack (not to scuttlebot because the networking bit is all in secret-stack)

**Comment by dominictarr** [comment]
@pfraze rfr

**Comment by pfraze** [comment]
:+1:

**Pull request merged**
