### PR TITLE
cleanup references to allow gc

### PR DESCRIPTION
**Pull request by pfraze**
trying to solve any possible memory leaks that are affect sbot

### CODE REVIEW

**Comment by pfraze** [comment]
i didnt de-allocate the buffer here https://github.com/ssbc/muxrpc/blob/9d0962caa7cf668983ddcbf6e1397836a5fee7fb/pull-weird.js#L14-L23 because it needs to persist until a pull-sink has finished draining it. the [async.js source test](https://github.com/ssbc/muxrpc/blob/9d0962caa7cf668983ddcbf6e1397836a5fee7fb/test/async.js#L47-L82) illustrates that situation. however, i'm concerned that we'll have undrained streams which never deallocate that buffer. any ideas on how we can deal with that?

**Comment by dominictarr** [comment]
I don't understand how this works, that test looks like everything should finish just fine.
If the sink stream doesn't drain, it's the sink's fault, not muxrpc's....

Hmm, since `waiting` is set null here https://github.com/ssbc/muxrpc/blob/9d0962caa7cf668983ddcbf6e1397836a5fee7fb/pull-weird.js#L30 can it ever call `done` when waiting is non-null?

**Comment by pfraze** [comment]
> I don't understand how this works, that test looks like everything should finish just fine.
If the sink stream doesn't drain, it's the sink's fault, not muxrpc's....

not sure... is pull-weird's `done()` getting called before it should be? or maybe there's a better time to do cleanup - [here, maybe?](https://github.com/ssbc/muxrpc/blob/9d0962caa7cf668983ddcbf6e1397836a5fee7fb/pull-weird.js#L45)

**Comment by dominictarr** [comment]
If there was something logically wrong with muxrpc we'd notice it in other ways...
Is there a way we can benchmark memory/resource usage better?
I got node-inspector working... but ironically it was really slow!
I've been thinking about parsing the protocol, and making a cli tool that can just pull out the memory profile,
then we can just have a test script that gets the memory use.

**Comment by pfraze** [comment]
http://strongloop.com/strongblog/how-to-heap-snapshots/ try this guy

**Comment by pfraze** [comment]
@dominictarr this PR fixes some memory leaks, but leaves the edge-case of holding onto a buffer that never gets drained. As that's the only issue, I suggest we merge and create a new issue to deal with the remaining leak

**Comment by pfraze** [comment]
Actually, I think the buffer will still get collected if undrained. The fns in the object returned by pull-weird should be the only remaining closures which capture the variable, and they should garbage-collect naturally. The pull-weird file really just needed to nullify the `weird` object, since the `weird.read` function captured `weird` and created the circular graph.

**Comment by dominictarr** [comment]
merged into 3.3.1

**Pull request merged**
